[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Security", "-C", "link-arg=-framework", "-C", "link-arg=CoreFoundation"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Security", "-C", "link-arg=-framework", "-C", "link-arg=CoreFoundation"]